-- DROP ALL TRINKEN TABLES
DROP TABLE tk_articulos CASCADE CONSTRAINTS;
DROP TABLE tk_ato_pedidos CASCADE CONSTRAINTS;
DROP TABLE tk_clientes CASCADE CONSTRAINTS;
DROP TABLE tk_drn_clientes CASCADE CONSTRAINTS;
DROP TABLE tk_pedidos CASCADE CONSTRAINTS;
DROP TABLE tk_proveedores CASCADE CONSTRAINTS;
DROP TABLE tk_repartidores CASCADE CONSTRAINTS;